dg_field_synonyms = {'account_balance': ['balance', 'acct_balance', 'available_funds'],
 'account_id': ['acct_id', 'account_identifier'],
 'account_number': ['acct_num', 'acc_no', 'account_no', 'acct_number'],
 'account_status': ['acct_status', 'status_of_account'],
 'account_type': ['acct_type', 'type_of_account'],
 'address': ['residence', 'location', 'home_address'],
 'approval_status': ['approval_state', 'loan_approval_status'],
 'assets': ['branch_assets', 'total_assets'],
 'beneficiary_account_number': ['beneficiary_acct_no', 'beneficiary_account'],
 'beneficiary_bank_details': ['beneficiary_bank_info', 'bank_details'],
 'beneficiary_id': ['beneficiary_number', 'beneficiary_identifier'],
 'beneficiary_name': ['name_of_beneficiary', 'beneficiary'],
 'branch_address': ['branch_location', 'branch_addr'],
 'branch_code': ['branch_identifier', 'branch_number'],
 'branch_contact_number': ['branch_phone', 'branch_contact'],
 'branch_id': ['branch_number', 'branch_no', 'branch_identifier'],
 'branch_name': ['name_of_branch', 'branch'],
 'card_id': ['card_number', 'card_identifier'],
 'card_number': ['card_no', 'number_on_card'],
 'cardholder_name': ['name_on_card', 'card_holder'],
 'cheque_number': ['check_no', 'cheque_no', 'check_number'],
 'complaint_date': ['date_of_complaint', 'complaint_day'],
 'complaint_description': ['description_of_complaint', 'complaint_details'],
 'complaint_id': ['complaint_number', 'complaint_identifier'],
 'complaint_status': ['status_of_complaint', 'complaint_state'],
 'complaint_subject': ['subject_of_complaint', 'complaint_topic'],
 'contact_number': ['phone', 'telephone', 'mobile_number'],
 'currency_code': ['curr_code', 'currency'],
 'currency_name': ['name_of_currency', 'currency'],
 'current_market_value': ['market_value', 'current_value'],
 'customer_id': ['cust_id', 'client_number', 'customer_number'],
 'customer_name': ['cust_name', 'client_name', 'name'],
 'customer_type': ['cust_type', 'client_type'],
 'cvv': ['security_code', 'card_verification_value'],
 'date_closed': ['closing_date', 'account_close_date'],
 'date_of_birth': ['dob', 'birth_date', 'birthdate'],
 'date_opened': ['opening_date', 'account_open_date'],
 'destination_account': ['to_account', 'destination_acct'],
 'duration': ['loan_term', 'tenure'],
 'email': ['email_address', 'e-mail', 'contact_email'],
 'email_notifications': 'email_notify',
 'employee_id': ['emp_id', 'staff_number', 'employee_number', 'emppp'],
 'employee_name': ['emp_name', 'staff_name'],
 'exchange_rate': ['fx_rate', 'conversion_rate'],
 'expiry_date': ['expiration_date', 'card_expiry'],
 'interest_rate': ['rate', 'int_rate', 'apr'],
 'investment_date': ['date_of_investment', 'investment_day'],
 'investment_id': ['investment_number', 'investment_identifier'],
 'investment_type': ['type_of_investment', 'investment_category'],
 'is_read': ['read_status', 'notification_read'],
 'kyc_status': ['know_your_customer_status', 'kyc'],
 'loan_amount': ['amount', 'loan_value', 'principal'],
 'loan_clearence': ['loan_clr'],
 'loan_end_date': ['end_date', 'loan_maturity_date'],
 'loan_id': ['loan_number', 'loan_no', 'loan_identifier'],
 'loan_start_date': ['start_date', 'loan_begin_date'],
 'loan_status': ['status_of_loan', 'loan_state'],
 'loan_type': ['type_of_loan', 'loan_category'],
 'maturity_date': ['date_of_maturity', 'maturity'],
 'message': ['notification_message', 'msg'],
 'notification_date': ['date_of_notification', 'notification_day'],
 'notification_id': ['notification_number', 'notification_identifier'],
 'outstanding_balance': ['remaining_balance', 'balance_due'],
 'password': ['passcode', 'pwd', 'login_password'],
 'payment_amount': ['amount_paid', 'payment_value'],
 'payment_date': ['date_of_payment', 'payment_day'],
 'payment_id': ['payment_number', 'payment_identifier'],
 'payment_method': ['method_of_payment', 'payment_mode'],
 'payment_status': ['status_of_payment', 'payment_state'],
 'payment_type': ['type_of_payment', 'payment_category'],
 'position': ['job_title', 'designation'],
 'purchase_price': ['buy_price', 'acquisition_cost'],
 'remarks': ['notes', 'comments', 'description'],
 'repayment_frequency': ['repayment_schedule', 'payment_frequency'],
 'salary': ['pay', 'wage', 'compensation'],
 'security_id': ['security_number', 'security_identifier'],
 'security_status': ['status_of_security', 'security_state'],
 'security_type': ['type_of_security', 'security_category'],
 'source_account': ['from_account', 'source_acct'],
 'transaction_amount': ['txn_amount', 'amount', 'transaction_value'],
 'transaction_date': ['txn_date', 'date_of_transaction'],
 'transaction_id': ['txn_id', 'transaction_number', 'txn_number'],
 'transaction_status': ['txn_status', 'status_of_transaction'],
 'transaction_type': ['txn_type', 'type_of_transaction'],
 'user_id': ['userid', 'user_identifier'],
 'username': ['user_name', 'login_id']}